substitutions:
  _REGION: us-west1
  _ENV: production

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

steps:
  # Deploy API Gateway using buildpacks
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api-gateway'
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'mangalm-api-gateway',
       '--source', './services/api-gateway',
       '--region', '${_REGION}',
       '--no-allow-unauthenticated',
       '--port', '3007',
       '--cpu', '2',
       '--memory', '1Gi',
       '--concurrency', '100',
       '--min-instances', '1',
       '--max-instances', '50',
       '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres',
       '--set-secrets', 'JWT_SECRET=jwt-secret:latest,DB_PASSWORD=db-password:latest',
       '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

  # Deploy AI Prediction Service using buildpacks
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-ai-prediction'
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'mangalm-ai-prediction',
       '--source', './services/ai-prediction-service',
       '--region', '${_REGION}',
       '--no-allow-unauthenticated',
       '--port', '3006',
       '--cpu', '2',
       '--memory', '2Gi',
       '--concurrency', '50',
       '--min-instances', '0',
       '--max-instances', '20',
       '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres',
       '--set-secrets', 'DB_PASSWORD=db-password:latest',
       '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

  # Deploy Document Processor using buildpacks
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-document-processor'
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'mangalm-document-processor',
       '--source', './services/document-processor',
       '--region', '${_REGION}',
       '--no-allow-unauthenticated',
       '--port', '3008',
       '--cpu', '2',
       '--memory', '2Gi',
       '--concurrency', '20',
       '--min-instances', '0',
       '--max-instances', '10',
       '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres',
       '--set-secrets', 'DB_PASSWORD=db-password:latest,OPENAI_API_KEY=openai-api-key:latest',
       '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

  # Get the API Gateway URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-api-gateway-url'
    waitFor: ['deploy-api-gateway']
    entrypoint: bash
    args:
      - '-c'
      - |
        API_URL=$(gcloud run services describe mangalm-api-gateway --region=${_REGION} --format='value(status.url)')
        echo "API Gateway URL: $$API_URL"
        echo $$API_URL > /workspace/api-gateway-url.txt

  # Deploy Sales Frontend using buildpacks with API Gateway URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-sales-frontend'
    waitFor: ['get-api-gateway-url']
    entrypoint: bash
    args:
      - '-c'
      - |
        API_URL=$(cat /workspace/api-gateway-url.txt)
        gcloud run deploy mangalm-sales-frontend \
          --source=./services/sales-frontend \
          --region=${_REGION} \
          --allow-unauthenticated \
          --port=3000 \
          --cpu=1 \
          --memory=512Mi \
          --concurrency=80 \
          --min-instances=0 \
          --max-instances=10 \
          --set-env-vars="REACT_APP_API_GATEWAY_URL=$$API_URL"

  # Zoho Integration Service - DISABLED FOR NOW
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-zoho-integration'
  #   entrypoint: gcloud
  #   args:
  #     ['run', 'deploy', 'mangalm-zoho-integration',
  #      '--source', './services/zoho-integration',
  #      '--region', '${_REGION}',
  #      '--no-allow-unauthenticated',
  #      '--port', '3005',
  #      '--cpu', '1',
  #      '--memory', '1Gi',
  #      '--concurrency', '50',
  #      '--min-instances', '0',
  #      '--max-instances', '10',
  #      '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres',
  #      '--set-secrets', 'DB_PASSWORD=db-password:latest',
  #      '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

timeout: 1800s