substitutions:
  _REGION: us-west1
  _ENV: production

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

steps:
  # Enable required APIs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'enable-apis'
    entrypoint: 'gcloud'
    args:
      - 'services'
      - 'enable'
      - 'sqladmin.googleapis.com'
      - 'run.googleapis.com'
      - 'secretmanager.googleapis.com'
      - 'cloudresourcemanager.googleapis.com'
      - 'iamcredentials.googleapis.com'
      - 'artifactregistry.googleapis.com'
      - '--project=$PROJECT_ID'

  # Create or verify secrets exist and grant permissions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'setup-secrets'
    waitFor: ['enable-apis']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking and creating necessary secrets..."

        # Check if db-password secret exists, create if not
        if ! gcloud secrets describe db-password --project=$PROJECT_ID &>/dev/null; then
          echo "Creating db-password secret..."
          echo -n "MangalmDB2024!Secure" | gcloud secrets create db-password --data-file=- --project=$PROJECT_ID
        else
          echo "db-password secret already exists"
        fi

        # Note: Secret Manager permissions must be granted manually once by an admin:
        # gcloud secrets add-iam-policy-binding db-password \
        #   --member="serviceAccount:445344153219-compute@developer.gserviceaccount.com" \
        #   --role="roles/secretmanager.secretAccessor" \
        #   --project=sales-assist-pilot
        echo "Note: Ensure service account has Secret Manager access (must be done manually)"

        echo "Secrets setup complete"

  # Deploy all backend services in parallel (they don't depend on each other for building)
  # Deploy API Gateway
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api-gateway'
    waitFor: ['setup-secrets']  # Only wait for secrets to be ready
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'mangalm-api-gateway',
       '--source', './services/api-gateway',
       '--platform', 'managed',
       '--region', '${_REGION}',
       '--allow-unauthenticated',
       '--port', '3007',
       '--cpu', '2',
       '--memory', '2Gi',
       '--concurrency', '100',
       '--min-instances', '1',
       '--max-instances', '50',
       '--timeout', '300',
       '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres,DISABLE_REDIS=true',
       '--set-secrets', 'DB_PASSWORD=db-password:latest',
       '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

  # Deploy Bulk Upload API in parallel
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-bulk-upload-api'
    waitFor: ['setup-secrets']  # Only wait for secrets to be ready
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'mangalm-bulk-upload-api',
       '--source', './services/bulk-upload-api',
       '--platform', 'managed',
       '--region', '${_REGION}',
       '--allow-unauthenticated',
       '--port', '3009',
       '--cpu', '2',
       '--memory', '4Gi',
       '--concurrency', '50',
       '--min-instances', '0',
       '--max-instances', '20',
       '--timeout', '900',
       '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres,DISABLE_REDIS=true',
       '--set-secrets', 'DB_PASSWORD=db-password:latest',
       '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

  # Deploy AI Prediction Service in parallel
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-ai-prediction'
    waitFor: ['setup-secrets']  # Only wait for secrets to be ready
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'mangalm-ai-prediction',
       '--source', './services/ai-prediction-service',
       '--platform', 'managed',
       '--region', '${_REGION}',
       '--allow-unauthenticated',
       '--port', '3001',
       '--cpu', '2',
       '--memory', '2Gi',
       '--concurrency', '50',
       '--min-instances', '0',
       '--max-instances', '20',
       '--timeout', '300',
       '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres,DISABLE_REDIS=true',
       '--set-secrets', 'DB_PASSWORD=db-password:latest',
       '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

  # Deploy Document Processor in parallel
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-document-processor'
    waitFor: ['setup-secrets']  # Only wait for secrets to be ready
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'mangalm-document-processor',
       '--source', './services/document-processor',
       '--platform', 'managed',
       '--region', '${_REGION}',
       '--allow-unauthenticated',
       '--port', '3008',
       '--cpu', '1',
       '--memory', '1Gi',
       '--concurrency', '20',
       '--min-instances', '0',
       '--max-instances', '5',
       '--timeout', '300',
       '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres,LIGHTWEIGHT_MODE=true',
       '--set-secrets', 'DB_PASSWORD=db-password:latest',
       '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

  # Get service URLs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-service-urls'
    waitFor: ['deploy-api-gateway', 'deploy-bulk-upload-api', 'deploy-ai-prediction', 'deploy-document-processor']
    entrypoint: bash
    args:
      - '-c'
      - |
        API_URL=$(gcloud run services describe mangalm-api-gateway --region=${_REGION} --format='value(status.url)')
        BULK_URL=$(gcloud run services describe mangalm-bulk-upload-api --region=${_REGION} --format='value(status.url)')
        AI_URL=$(gcloud run services describe mangalm-ai-prediction --region=${_REGION} --format='value(status.url)')
        DOC_URL=$(gcloud run services describe mangalm-document-processor --region=${_REGION} --format='value(status.url)')

        echo "API Gateway URL: $$API_URL"
        echo "Bulk Upload API URL: $$BULK_URL"
        echo "AI Prediction URL: $$AI_URL"
        echo "Document Processor URL: $$DOC_URL"

        echo $$API_URL > /workspace/api-gateway-url.txt
        echo $$BULK_URL > /workspace/bulk-upload-url.txt
        echo $$AI_URL > /workspace/ai-prediction-url.txt
        echo $$DOC_URL > /workspace/document-processor-url.txt

  # Update API Gateway with service URLs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-api-gateway'
    waitFor: ['get-service-urls']
    entrypoint: bash
    args:
      - '-c'
      - |
        BULK_URL=$(cat /workspace/bulk-upload-url.txt)
        AI_URL=$(cat /workspace/ai-prediction-url.txt)
        DOC_URL=$(cat /workspace/document-processor-url.txt)

        gcloud run services update mangalm-api-gateway \
          --region=${_REGION} \
          --update-env-vars="BULK_UPLOAD_API_URL=$$BULK_URL,AI_PREDICTION_URL=$$AI_URL,DOCUMENT_PROCESSOR_URL=$$DOC_URL"

  # Deploy Sales Frontend using buildpacks with service URLs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-sales-frontend'
    waitFor: ['update-api-gateway']
    entrypoint: bash
    args:
      - '-c'
      - |
        API_URL=$(cat /workspace/api-gateway-url.txt)
        BULK_URL=$(cat /workspace/bulk-upload-url.txt)
        DOC_URL=$(cat /workspace/document-processor-url.txt)
        AI_URL=$(cat /workspace/ai-prediction-url.txt)

        gcloud run deploy mangalm-sales-frontend \
          --source=./services/sales-frontend \
          --platform=managed \
          --region=${_REGION} \
          --allow-unauthenticated \
          --port=3000 \
          --cpu=2 \
          --memory=1Gi \
          --concurrency=80 \
          --min-instances=0 \
          --max-instances=10 \
          --timeout=300 \
          --set-env-vars="NODE_ENV=production,REACT_APP_API_GATEWAY_URL=$$API_URL,REACT_APP_BULK_UPLOAD_API_URL=$$BULK_URL,REACT_APP_DOCUMENT_PROCESSOR_URL=$$DOC_URL,REACT_APP_AI_PREDICTION_URL=$$AI_URL"

  # Update all backend services with frontend URL for CORS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'configure-cors'
    waitFor: ['deploy-sales-frontend']
    entrypoint: bash
    args:
      - '-c'
      - |
        FRONTEND_URL=$(gcloud run services describe mangalm-sales-frontend --region=${_REGION} --format='value(status.url)')
        echo "Configuring CORS for frontend URL: $$FRONTEND_URL"

        # Update all services with CORS configuration
        gcloud run services update mangalm-api-gateway \
          --region=${_REGION} \
          --update-env-vars="CORS_ALLOWED_ORIGINS=$$FRONTEND_URL"

        gcloud run services update mangalm-bulk-upload-api \
          --region=${_REGION} \
          --update-env-vars="CORS_ALLOWED_ORIGINS=$$FRONTEND_URL"

        gcloud run services update mangalm-ai-prediction \
          --region=${_REGION} \
          --update-env-vars="CORS_ALLOWED_ORIGINS=$$FRONTEND_URL"

        gcloud run services update mangalm-document-processor \
          --region=${_REGION} \
          --update-env-vars="CORS_ALLOWED_ORIGINS=$$FRONTEND_URL"

  # Zoho Integration Service - DISABLED FOR NOW
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: 'deploy-zoho-integration'
  #   entrypoint: gcloud
  #   args:
  #     ['run', 'deploy', 'mangalm-zoho-integration',
  #      '--source', './services/zoho-integration',
  #      '--region', '${_REGION}',
  #      '--no-allow-unauthenticated',
  #      '--port', '3005',
  #      '--cpu', '1',
  #      '--memory', '1Gi',
  #      '--concurrency', '50',
  #      '--min-instances', '0',
  #      '--max-instances', '10',
  #      '--set-env-vars', 'NODE_ENV=production,DB_HOST=/cloudsql/$PROJECT_ID:${_REGION}:mangalm-db,DB_PORT=5432,DB_NAME=mangalm_sales,DB_USER=postgres',
  #      '--set-secrets', 'DB_PASSWORD=db-password:latest',
  #      '--add-cloudsql-instances', '$PROJECT_ID:${_REGION}:mangalm-db']

  # Final deployment summary
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deployment-summary'
    waitFor: ['configure-cors']
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "========================================="
        echo "DEPLOYMENT SUMMARY"
        echo "========================================="
        echo ""
        echo "Deployed Services:"
        echo ""

        # Get all service URLs
        FRONTEND_URL=$(gcloud run services describe mangalm-sales-frontend --region=${_REGION} --format='value(status.url)')
        API_URL=$(gcloud run services describe mangalm-api-gateway --region=${_REGION} --format='value(status.url)')
        BULK_URL=$(gcloud run services describe mangalm-bulk-upload-api --region=${_REGION} --format='value(status.url)')
        AI_URL=$(gcloud run services describe mangalm-ai-prediction --region=${_REGION} --format='value(status.url)')
        DOC_URL=$(gcloud run services describe mangalm-document-processor --region=${_REGION} --format='value(status.url)')

        echo "Sales Frontend: $$FRONTEND_URL"
        echo "API Gateway: $$API_URL"
        echo "Bulk Upload API: $$BULK_URL"
        echo "AI Prediction Service: $$AI_URL"
        echo "Document Processor: $$DOC_URL"
        echo ""
        echo "========================================="
        echo "Access your application at: $$FRONTEND_URL"
        echo "========================================="

timeout: 1800s