# Prometheus Configuration for Enterprise Bulk Upload System
# 10/10 Monitoring Architecture

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mangalm-bulk-upload'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# Alert rules
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          database: 'mangalm_sales'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Application metrics (Node.js)
  - job_name: 'bulk-upload-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'host.docker.internal:3000'
        - 'host.docker.internal:3002'
        - 'host.docker.internal:3003'
        labels:
          service: 'bulk-upload'
          component: 'api'

  # Bull Queue metrics
  - job_name: 'bull-exporter'
    static_configs:
      - targets: ['bull-exporter:9538']
        labels:
          service: 'bull-queues'

  # MinIO metrics
  - job_name: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: ['minio:9000']
        labels:
          service: 'minio'

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'docker'

# Service discovery for dynamic targets
# file_sd_configs:
#   - files:
#     - '/etc/prometheus/targets/*.json'
#     refresh_interval: 30s