# Buildpack configuration for document-processor
[build]
  [[build.env]]
    name = "GOOGLE_BUILDABLE"
    value = "dist"

  [[build.env]]
    name = "NODE_ENV"
    value = "production"

[[build.buildpacks]]
  id = "google.nodejs.runtime"

[[build.buildpacks]]
  id = "google.nodejs.npm"

[[build.buildpacks]]
  id = "google.nodejs.typescript"

[build.env]
  NODE_OPTIONS = "--max-old-space-size=2048"